import { resolve } from "node:path";
import { StaticRegistryError } from "./errors.ts";
import { buildStaticRegistryFragment } from "./fragment.ts";
import type {
    StaticRegistryBuildResult,
    StaticRegistryGenerateResult,
    StaticRegistryGeneratorConfig,
} from "./types.ts";

export async function buildStaticRegistryModule(
    config: StaticRegistryGeneratorConfig,
): Promise<StaticRegistryBuildResult> {
    const outputPath = resolve(config.outputPath);
    const fragment = await buildStaticRegistryFragment(config);
    const content = `// Generated by @kuma-00/bot-kit-registry. Do not edit.
${fragment.imports.join("\n")}

export const ${config.exportName} = [${fragment.identifiers.join(", ")}] as const;
`;
    return {
        content,
        entryCount: fragment.entryCount,
        outputPath,
    };
}

export async function generateStaticRegistry(
    config: StaticRegistryGeneratorConfig,
): Promise<StaticRegistryGenerateResult> {
    const generated = await buildStaticRegistryModule(config);
    const current = (await Bun.file(generated.outputPath).exists())
        ? await Bun.file(generated.outputPath).text()
        : undefined;
    const changed = current !== generated.content;
    if (changed) await Bun.write(generated.outputPath, generated.content);
    return {
        changed,
        entryCount: generated.entryCount,
        outputPath: generated.outputPath,
    };
}

export async function checkStaticRegistry(
    config: StaticRegistryGeneratorConfig,
): Promise<StaticRegistryGenerateResult> {
    const generated = await buildStaticRegistryModule(config);
    const current = (await Bun.file(generated.outputPath).exists())
        ? await Bun.file(generated.outputPath).text()
        : undefined;
    if (current !== generated.content) {
        throw new StaticRegistryError(
            "stale",
            `Generated static registry is stale: ${generated.outputPath}`,
        );
    }
    return {
        changed: false,
        entryCount: generated.entryCount,
        outputPath: generated.outputPath,
    };
}
