import { resolve } from "node:path";
import { assertIdentifier } from "./discovery.ts";
import { StaticRegistryError } from "./errors.ts";
import { buildStaticRegistryFragment } from "./fragment.ts";
import type {
    StaticRegistryGroupBuildResult,
    StaticRegistryGroupConfig,
    StaticRegistryGroupGenerateResult,
} from "./types.ts";

function validateGroup(config: StaticRegistryGroupConfig): void {
    const exportNames = new Set<string>();
    for (const registry of config.registries) {
        assertIdentifier(registry.exportName, "exportName");
        if (exportNames.has(registry.exportName)) {
            throw new StaticRegistryError(
                "duplicate-export-name",
                `Duplicate grouped registry export name: ${registry.exportName}`,
            );
        }
        exportNames.add(registry.exportName);
    }
}

function groupIdentifierPrefix(
    groupIndex: number,
    exportNames: ReadonlySet<string>,
): string {
    let prefix = `registryGroup${groupIndex}Item`;
    while (
        [...exportNames].some(
            (exportName) =>
                exportName.startsWith(prefix) &&
                /^\d+$/.test(exportName.slice(prefix.length)),
        )
    ) {
        prefix += "_";
    }
    return prefix;
}

/** Builds deterministic source for multiple readonly registries without writing it. */
export async function buildStaticRegistryGroupModule(
    config: StaticRegistryGroupConfig,
): Promise<StaticRegistryGroupBuildResult> {
    validateGroup(config);
    const outputPath = resolve(config.outputPath);
    const imports: string[] = [];
    const exports: string[] = [];
    const entryCountEntries: [string, number][] = [];
    const exportNames = new Set(
        config.registries.map((registry) => registry.exportName),
    );

    for (const [index, registry] of config.registries.entries()) {
        const fragment = await buildStaticRegistryFragment(
            { ...registry, outputPath },
            groupIdentifierPrefix(index, exportNames),
        );
        imports.push(...fragment.imports);
        exports.push(
            `/** Deterministic readonly registry generated from source modules. */\nexport const ${registry.exportName} = [${fragment.identifiers.join(", ")}] as const;`,
        );
        entryCountEntries.push([registry.exportName, fragment.entryCount]);
    }

    const content = `// Generated by @kuma-00/bot-kit-registry. Do not edit.
${imports.join("\n")}

${exports.join("\n\n")}
`;
    const entryCounts = Object.fromEntries(entryCountEntries);
    return { content, entryCounts, outputPath };
}

/** Writes grouped static registries only when their deterministic content changed. */
export async function generateStaticRegistryGroup(
    config: StaticRegistryGroupConfig,
): Promise<StaticRegistryGroupGenerateResult> {
    const generated = await buildStaticRegistryGroupModule(config);
    const current = (await Bun.file(generated.outputPath).exists())
        ? await Bun.file(generated.outputPath).text()
        : undefined;
    const changed = current !== generated.content;
    if (changed) await Bun.write(generated.outputPath, generated.content);
    return {
        changed,
        entryCounts: generated.entryCounts,
        outputPath: generated.outputPath,
    };
}

/**
 * Verifies that committed grouped registries match all source modules.
 *
 * @throws {StaticRegistryError} When generated content is stale or invalid.
 */
export async function checkStaticRegistryGroup(
    config: StaticRegistryGroupConfig,
): Promise<StaticRegistryGroupGenerateResult> {
    const generated = await buildStaticRegistryGroupModule(config);
    const current = (await Bun.file(generated.outputPath).exists())
        ? await Bun.file(generated.outputPath).text()
        : undefined;
    if (current !== generated.content) {
        throw new StaticRegistryError(
            "stale",
            `Generated grouped static registry is stale: ${generated.outputPath}`,
        );
    }
    return {
        changed: false,
        entryCounts: generated.entryCounts,
        outputPath: generated.outputPath,
    };
}
