import { resolve } from "node:path";
import {
    buildStaticRegistryFragment,
    StaticRegistryError,
    type StaticRegistryFragment,
    type StaticRegistryValidator,
} from "@kuma-00/bot-kit-registry";
import { RegistryValidationError } from "./errors.ts";

const BOT_PACKAGE_NAME = "@kuma-00/bot-kit-bot";

export interface BotRegistryGeneratorConfig {
    readonly commandSourceDir: string;
    readonly eventSourceDir: string;
    readonly outputPath: string;
}

export interface GenerateBotRegistryResult {
    readonly changed: boolean;
    readonly commandCount: number;
    readonly eventCount: number;
    readonly outputPath: string;
}

export function defineBotRegistryConfig<
    const T extends BotRegistryGeneratorConfig,
>(config: T): T {
    return config;
}

function validateCommand(value: unknown, file: string): true {
    const valid =
        typeof value === "object" &&
        value !== null &&
        typeof (value as { id?: unknown }).id === "string" &&
        typeof (value as { kind?: unknown }).kind === "string" &&
        "builder" in value;
    if (!valid) {
        throw new RegistryValidationError(
            "invalid-module",
            `${file} must default export a valid bot command`,
        );
    }
    return true;
}

function validateEvent(value: unknown, file: string): true {
    const valid =
        typeof value === "object" &&
        value !== null &&
        typeof (value as { id?: unknown }).id === "string" &&
        typeof (value as { event?: unknown }).event === "string" &&
        typeof (value as { execute?: unknown }).execute === "function";
    if (!valid) {
        throw new RegistryValidationError(
            "invalid-module",
            `${file} must default export a valid bot event`,
        );
    }
    return true;
}

async function buildBotFragment(
    sourceDir: string,
    outputPath: string,
    exportName: string,
    identifierPrefix: string,
    validate: StaticRegistryValidator,
): Promise<StaticRegistryFragment> {
    try {
        return await buildStaticRegistryFragment(
            {
                sourceDir,
                outputPath,
                exportName,
                validate,
            },
            identifierPrefix,
        );
    } catch (error) {
        if (!(error instanceof StaticRegistryError)) throw error;
        throw new RegistryValidationError(
            error.code === "empty-source" ? "empty-source" : "invalid-module",
            error.message,
        );
    }
}

export async function buildBotRegistryModule(
    config: BotRegistryGeneratorConfig,
): Promise<{
    readonly content: string;
    readonly commandCount: number;
    readonly eventCount: number;
}> {
    const outputPath = resolve(config.outputPath);
    const commands = await buildBotFragment(
        config.commandSourceDir,
        outputPath,
        "commands",
        "command",
        (value, { file }) => validateCommand(value, file),
    );
    const events = await buildBotFragment(
        config.eventSourceDir,
        outputPath,
        "events",
        "event",
        (value, { file }) => validateEvent(value, file),
    );
    const content = `// Generated by ${BOT_PACKAGE_NAME}. Do not edit.
import {
    createBotRegistry,
    createDiscordBot as createRuntimeDiscordBot,
    type DiscordBotRuntimeOptions,
} from "${BOT_PACKAGE_NAME}";
${[...commands.imports, ...events.imports].join("\n")}

export const botRegistry = createBotRegistry([${commands.identifiers.join(", ")}], [${events.identifiers.join(", ")}]);
export const applicationCommands = botRegistry.applicationCommands;
export const createGeneratedDiscordBot = (
    options: DiscordBotRuntimeOptions,
) => createRuntimeDiscordBot(botRegistry, options);
`;
    return {
        content,
        commandCount: commands.entryCount,
        eventCount: events.entryCount,
    };
}

export async function generateBotRegistry(
    config: BotRegistryGeneratorConfig,
): Promise<GenerateBotRegistryResult> {
    const generated = await buildBotRegistryModule(config);
    const outputPath = resolve(config.outputPath);
    const current = (await Bun.file(outputPath).exists())
        ? await Bun.file(outputPath).text()
        : undefined;
    const changed = current !== generated.content;
    if (changed) await Bun.write(outputPath, generated.content);
    return {
        changed,
        commandCount: generated.commandCount,
        eventCount: generated.eventCount,
        outputPath,
    };
}

export async function checkBotRegistry(
    config: BotRegistryGeneratorConfig,
): Promise<GenerateBotRegistryResult> {
    const generated = await buildBotRegistryModule(config);
    const outputPath = resolve(config.outputPath);
    const current = (await Bun.file(outputPath).exists())
        ? await Bun.file(outputPath).text()
        : undefined;
    if (current !== generated.content) {
        throw new Error(
            `Generated bot registry is stale: ${outputPath}. Run generateBotRegistry().`,
        );
    }
    return {
        changed: false,
        commandCount: generated.commandCount,
        eventCount: generated.eventCount,
        outputPath,
    };
}
