import { dirname, relative, resolve, sep } from "node:path";
import { pathToFileURL } from "node:url";
import { RegistryValidationError } from "./errors.ts";

const BOT_PACKAGE_NAME = "@kuma-00/bot-kit-bot";

export interface BotRegistryGeneratorConfig {
    readonly commandSourceDir: string;
    readonly eventSourceDir: string;
    readonly outputPath: string;
}

export interface GenerateBotRegistryResult {
    readonly changed: boolean;
    readonly commandCount: number;
    readonly eventCount: number;
    readonly outputPath: string;
}

export function defineBotRegistryConfig<
    const T extends BotRegistryGeneratorConfig,
>(config: T): T {
    return config;
}

function isRuntimeModule(path: string): boolean {
    return (
        path.endsWith(".ts") &&
        !path.endsWith(".d.ts") &&
        !path.endsWith(".test.ts") &&
        !path.endsWith(".spec.ts")
    );
}

async function discoverModules(
    sourceDir: string,
    outputPath: string,
): Promise<string[]> {
    const absoluteSource = resolve(sourceDir);
    const absoluteOutput = resolve(outputPath);
    const files: string[] = [];
    for await (const path of new Bun.Glob("**/*.ts").scan(absoluteSource)) {
        const absolutePath = resolve(absoluteSource, path);
        if (absolutePath !== absoluteOutput && isRuntimeModule(path)) {
            files.push(absolutePath);
        }
    }
    files.sort();
    if (files.length === 0) {
        throw new RegistryValidationError(
            "empty-source",
            `No runtime TypeScript modules found in ${absoluteSource}`,
        );
    }
    return files;
}

function moduleImportPath(outputPath: string, modulePath: string): string {
    let path = relative(dirname(outputPath), modulePath).split(sep).join("/");
    if (!path.startsWith(".")) path = `./${path}`;
    return path;
}

async function validateDefaultExports(
    files: readonly string[],
    expected: "command" | "event",
): Promise<void> {
    for (const file of files) {
        const loaded = (await import(pathToFileURL(file).href)) as {
            default?: unknown;
        };
        const value = loaded.default;
        const valid =
            typeof value === "object" &&
            value !== null &&
            typeof (value as { id?: unknown }).id === "string" &&
            (expected === "event"
                ? typeof (value as { event?: unknown }).event === "string" &&
                  typeof (value as { execute?: unknown }).execute === "function"
                : typeof (value as { kind?: unknown }).kind === "string" &&
                  "builder" in value);
        if (!valid) {
            throw new RegistryValidationError(
                "invalid-module",
                `${file} must default export a valid bot ${expected}`,
            );
        }
    }
}

export async function buildBotRegistryModule(
    config: BotRegistryGeneratorConfig,
): Promise<{
    readonly content: string;
    readonly commandCount: number;
    readonly eventCount: number;
}> {
    const outputPath = resolve(config.outputPath);
    const commandFiles = await discoverModules(
        config.commandSourceDir,
        outputPath,
    );
    const eventFiles = await discoverModules(config.eventSourceDir, outputPath);
    await validateDefaultExports(commandFiles, "command");
    await validateDefaultExports(eventFiles, "event");

    const imports = [
        ...commandFiles.map(
            (file, index) =>
                `import command${index} from ${JSON.stringify(moduleImportPath(outputPath, file))};`,
        ),
        ...eventFiles.map(
            (file, index) =>
                `import event${index} from ${JSON.stringify(moduleImportPath(outputPath, file))};`,
        ),
    ];
    const commands = commandFiles
        .map((_, index) => `command${index}`)
        .join(", ");
    const events = eventFiles.map((_, index) => `event${index}`).join(", ");
    const content = `// Generated by ${BOT_PACKAGE_NAME}. Do not edit.
import {
    createBotRegistry,
    createDiscordBot as createRuntimeDiscordBot,
    type DiscordBotRuntimeOptions,
} from "${BOT_PACKAGE_NAME}";
${imports.join("\n")}

export const botRegistry = createBotRegistry([${commands}], [${events}]);
export const applicationCommands = botRegistry.applicationCommands;
export const createGeneratedDiscordBot = (
    options: DiscordBotRuntimeOptions,
) => createRuntimeDiscordBot(botRegistry, options);
`;
    return {
        content,
        commandCount: commandFiles.length,
        eventCount: eventFiles.length,
    };
}

export async function generateBotRegistry(
    config: BotRegistryGeneratorConfig,
): Promise<GenerateBotRegistryResult> {
    const generated = await buildBotRegistryModule(config);
    const outputPath = resolve(config.outputPath);
    const current = (await Bun.file(outputPath).exists())
        ? await Bun.file(outputPath).text()
        : undefined;
    const changed = current !== generated.content;
    if (changed) await Bun.write(outputPath, generated.content);
    return {
        changed,
        commandCount: generated.commandCount,
        eventCount: generated.eventCount,
        outputPath,
    };
}

export async function checkBotRegistry(
    config: BotRegistryGeneratorConfig,
): Promise<GenerateBotRegistryResult> {
    const generated = await buildBotRegistryModule(config);
    const outputPath = resolve(config.outputPath);
    const exists = await Bun.file(outputPath).exists();
    const current = exists ? await Bun.file(outputPath).text() : undefined;
    if (current !== generated.content) {
        throw new Error(
            `Generated bot registry is stale: ${outputPath}. Run generateBotRegistry().`,
        );
    }
    return {
        changed: false,
        commandCount: generated.commandCount,
        eventCount: generated.eventCount,
        outputPath,
    };
}
