// Generated by @kuma-00/bot-kit-bot. Do not edit.
import {
    type BotRegistryClient,
    type BotRegistryServices,
    createBotRegistry,
    createDiscordBot as createRuntimeDiscordBot,
    type DiscordBotRuntimeOptions,
} from "@kuma-00/bot-kit-bot";
import command0 from "./commands/menu.ts";
import command1 from "./commands/root.ts";
import command2 from "./commands/sub.ts";
import event0 from "./events/ready.ts";

/** Validated command and event registry generated from consumer modules. */
export const botRegistry = createBotRegistry(
    [
        // Commands sorted by module path.
        command0,
        command1,
        command2,
    ],
    [
        // Events sorted by module path.
        event0,
    ],
);
/** Discord REST application-command payloads composed from the registry. */
export const applicationCommands = botRegistry.applicationCommands;
/** Creates a Discord bot bound to the generated registry. */
export const createGeneratedDiscordBot = (
    options: DiscordBotRuntimeOptions<
        BotRegistryClient<typeof botRegistry>,
        BotRegistryServices<typeof botRegistry>
    >,
) => createRuntimeDiscordBot(botRegistry, options);
